### ISSUE TITLE
What does the name mean?

### ISSUE THREAD

**Issue by gvanrossum** [facundobatista/foffinf#2]
Color me dense, but this module's name mystifies me. Is it a meme? A pun? Should I `s/f/s/`?

Other than that, this looks very handy! Well done.

**Comment by ljnsn** [comment]
I believe it stands for "logging", but with fs because f-strings. This eluded me as well though, only got it after looking at the code.

**Comment by facundobatista** [comment]
Yeah, right, it's an "all Fs logging" :p

Naming things is hard :)
